<?php

########################################################################
# Extension Manager/Repository config file for ext: "marit_linklist"
#
# Auto generated by Extbase Kickstarter 2010-03-19
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Extbase Linklist',
	'description' => 'Linklist',
	'category' => 'plugin',
	'author' => 'Marit AG, Lina Wolf',
	'author_email' => 'extensions@marit.ag',
	'author_company' => 'Marit AG',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>